<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Tables\Controllers\TableController;
use Illuminate\Support\Facades\Route;

Route::get('tables', [TableController::class, 'getTables']);
Route::post('tables', [TableController::class, 'addTable']);
Route::get('tables/{id}', [TableController::class, 'getTable']);
Route::put('tables/{id}', [TableController::class, 'editTable']);
Route::delete('tables/{id}', [TableController::class, 'deleteTable']);
