services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - tables-network
        depends_on:
            - postgres

    postgres:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db_data:/var/lib/postgresql/data'
        networks:
            - tables-network

networks:
    tables-network:
        driver: bridge

volumes:
    db_data:
        driver: local