openapi: 3.0.3
info:
  title: Tables
  description: Производит хранение, поиск и управление столиками
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
tags:
  - name: tables
paths:
  /tables:
    get:
      tags:
        - tables
      x-lg-handler: 'App\Http\ApiV1\Modules\Tables\Controllers\TableController@create'
      summary: Список столиков
      description: Список столиков
      operationId: 'listTables'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      tags:
        - tables
      summary: Добавление столика
      description: Добавление столика
      operationId: 'addTable'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Table'
        required: true
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /tables/{id}:
    get:
      tags:
        - tables
      summary: Столик
      description: Столик
      operationId: 'getTable'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - tables
      summary: Редактирование столика
      description: Редактирование столика
      operationId: 'editTable'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Table'
        required: true
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - tables
      summary: Удаление столика
      description: Удаление столика
      operationId: 'deleteTable'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешный ответ
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  
components:
  schemas:
    Table:
      type: object
      properties:
        id:
          type: integer
        seats:
          type: integer
        location:
          type: string
      required:
        - id
        - seats
        - location
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Not Found
  responses:
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Table'
    ServerError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
