openapi: 3.0.3
info:
  title: Tables
  description: Производит хранение, поиск и управление столиками
  version: 1.0.0
servers:
  - url: '/api/v1'
tags:
  - name: tables
paths:
  /tables:
    get:
      tags:
        - tables
      x-lg-handler: 'App\Http\ApiV1\Modules\Tables\Controllers\TableController@getTables'
      summary: Список столиков
      description: Список столиков
      operationId: 'listTables'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './tables/tables.yaml#/TablesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      tags:
        - tables
      x-lg-handler: 'App\Http\ApiV1\Modules\Tables\Controllers\TableController@addTable'
      summary: Добавление столика
      description: Добавление столика
      operationId: 'addTable'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './tables/tables.yaml#/AddTableRequest'
        required: true
      responses:
        '201':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './tables/tables.yaml#/TableResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  /tables/{id}:
    get:
      tags:
        - tables
      x-lg-handler: 'App\Http\ApiV1\Modules\Tables\Controllers\TableController@getTable'
      summary: Столик
      description: Столик
      operationId: 'getTable'
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './tables/tables.yaml#/TableResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - tables
      x-lg-handler: 'App\Http\ApiV1\Modules\Tables\Controllers\TableController@editTable'
      summary: Редактирование столика
      description: Редактирование столика
      operationId: 'editTable'
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './tables/tables.yaml#/Table'
        required: true
      responses:
        '204':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyDataResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - tables
      x-lg-handler: 'App\Http\ApiV1\Modules\Tables\Controllers\TableController@deleteTable'
      summary: Удаление столика
      description: Удаление столика
      operationId: 'deleteTable'
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '204':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyDataResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  
components:
  parameters:
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Not Found
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
